# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8006
  connection-timeout: 5000ms
  servlet:
    context-path: /mcp-server-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-wz93zg93v8pu4w6o8.mysql.rds.aliyuncs.com:3306/mcp-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: hscm_admin
      password: Hscm_admin
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# 获取序列的路径
seqCodeUrl: http://120.79.54.184:8004/mcp-server-admin/org/syssequence/selectvalue/

key: e1153123d7d180ceeb820d577ff119876678