server:
  port: 10004
  
spring:
  profiles:
    active: native

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10001/eureka/
